services:
  prometheus:
    image: prom/prometheus:v3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./scrape_configs:/etc/prometheus/scrape_configs:ro
    ports:
      - "9090:9090"
      
  cadvisor:
    image: ghcr.io/google/cadvisor:0.60.3
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
