persistence:
  enabled: true
  size: 10Gi

tempo:
  multitenancyEnabled: false
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal
