grafana:
    enabled: false

alertmanager:
    enabled: true

defaultRules:
    create: false

prometheus:
    enabled: true

kubeControllerManager:
    enabled: false

kubeScheduler:
    enabled: false

kubeEtcd:
    enabled: false

kubeProxy:
    enabled: false
