server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # This route will always return a 500 error
    location /error {
        return 500 "Simulated 500 Internal Server Error\n";
    }
}
